language: rust
before_install:
    - cd server
after_success: |
    cargo clean && sh doc.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: test
env:
  global:
    secure: "iMlC7KnJ1uQBmIk4pd1VPmBX6dyh4Soak9bIl4T9QIrllLf3LtKhmfJf/BM3g2dH5aX3RMAF4z4dpyOVqTVllWnPU6Ujts9Kj35gtL+hgfA5yGUP1cwtrILYNUt7z40n3gI3pP/VEaeaTyZQPYxD8428SdxzfoJ2auoPBHnHjUeyWEvjarZGBcSdp+KXPDnO5v79PUwmzEcGMWf/0MYNvRUtBJPezAzIeSiL/xyMivffT9kzMEFd5LqM87H8jabn6W4ElR+SVCQNlzy4wJ7WJt1fXI37Y7R8KDrGmqOye9QREBHX4de+Oln3SAvsrOTXnLsWT+52TJpfz04S940X6TE7IT/UrKrh8gRDVbFEHJdEPiHhnb9SSVdaUBUIeUunmFOVtND1L89SQbMViFeaPZm+aqa9w/pOHvoFOTTwGGHhkdU6qU7ISIppbpFMGzCAKs+9LbWELAkgQaSIaWwwB2qFy+S6J+CuOLOiPlE0GgzvFBxkuXzBzIgmTZWuQNEO6TRunWeP2fl5b0mrqaP+Ypv+1zB9tlTCP3DpsSFaU2PnMT8oxuSZJvDX6RhgmS6/HnFFi+rLINXPUq65sz28vmNxDjEpg7ARi6CijL3N0qqTLe1iKGbogfACUgQPT+4iiXoWAYzXYVjHc2eWzbgd9zxgAAX5UO4iW1vgBoTe660="
